apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velociraptor-data-pvc
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}