tasks:
  - name: all
    description: Checks the kubernetes cluster for Velociraptor
    actions:
      - description: Velociraptor Frontend Health Check
        wait:
          cluster:
            kind: Deployment
            name: velociraptor
            namespace: velociraptor
            condition: Available

      - description: Velociraptor Pod Status Check
        cmd: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=velociraptor -n velociraptor --timeout=60s
          echo "Velociraptor pods are ready"

  - name: placeholder
    actions:
      - cmd: kubectl get pods -n velociraptor
      - cmd: kubectl get secrets -n velociraptor
      - cmd: kubectl get packages -n velociraptor
      - cmd: kubectl get events -n velociraptor
