apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: velociraptor
spec:
{{- if .Values.uds.sso.enabled }}
  sso:
    - name: Velociraptor Login
      clientId: uds-package-velociraptor
      redirectUris:
        - "https://velociraptor.{{ .Values.uds.domain }}/auth/oidc/keycloak/callback"
      secretName: velociraptor-sso-client
      protocol: openid-connect
      standardFlowEnabled: true
      serviceAccountsEnabled: false
      publicClient: false
      authorizationServicesEnabled: false
      directAccessGrantsEnabled: false
      implicitFlowEnabled: false
{{- end }}
  # Customize network policies and expose services via istio
  network:
    expose:
      - service: velociraptor
        selector:
          app.kubernetes.io/name: velociraptor
        gateway: tenant
        host: velociraptor
        port: 8889
    allow:
      - direction: Ingress
        remoteGenerated: Anywhere

      - direction: Egress
        remoteGenerated: Anywhere

    # Custom rules for unanticipated scenarios
    {{- with .Values.additionalNetworkAllow }}
    {{ toYaml . | nindent 6 }}
    {{- end }}
